name: Generate SBOM using Microsoft SBOM Tool

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-sbom:
    name: Generate SBOM (MS Tool)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # or 7.0/6.0 as per your project

      - name: Restore NuGet packages
        run: dotnet restore eShopOnWeb.sln

      - name: Download MS SBOM Tool
        run: |
          wget https://github.com/microsoft/sbom-tool/releases/download/v1.0.8/sbom-tool-linux-x64.tar.gz
          mkdir sbom-tool
          tar -xvzf sbom-tool-linux-x64.tar.gz -C sbom-tool
          chmod +x sbom-tool/sbom-tool

      - name: Generate SBOM
        run: |
          ./sbom-tool/sbom-tool generate \
            --build-drop-path . \
            --manifest-dir sbom-output \
            --package-name "MyNuGetApp" \
            --package-version "1.0.0" \
            --verbose

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom-output/
