name: Generate SBOM for .NET NuGet Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom-dotnet:
    name: Generate SBOM using Microsoft SBOM Tool
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up .NET SDK that supports .NET 8.0
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Detect solution or project file and store path in an environment variable
      - name: Find Solution or Project File
        id: find-project
        run: |
          FILE=$(find . -maxdepth 1 \( -name "*.sln" -o -name "*.csproj" \) | head -n 1)
          if [ -z "$FILE" ]; then
            echo "No .sln or .csproj file found in root directory."
            exit 1
          fi
          echo "project_path=$FILE" >> $GITHUB_OUTPUT

      # Restore dependencies and build the project or solution
      - name: Restore and Build
        run: |
          dotnet restore "${{ steps.find-project.outputs.project_path }}"
          dotnet build "${{ steps.find-project.outputs.project_path }}" -c Release

      # Install Microsoft SBOM tool (v1.3.2 as latest assets may be missing)
      - name: Install SBOM Tool
        run: |
          wget https://github.com/microsoft/sbom-tool/releases/download/v1.3.2/sbom-tool-linux-x64.tar.gz
          mkdir sbom-tool
          tar -xzf sbom-tool-linux-x64.tar.gz -C sbom-tool
          chmod +x sbom-tool/sbom-tool

      # Run the SBOM tool on build output
      - name: Generate SBOM (SPDX JSON)
        run: |
          ./sbom-tool/sbom-tool generate \
            --build-drop-path ./bin/Release \
            --package-name MyDotNetApp \
            --package-version 1.0.0 \
            --output-path ./sbom \
            --formats spdxjson

      # Upload the SBOM file as an artifact
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-dotnet
          path: ./sbom
