name: Generate SBOM using Microsoft SBOM Tool

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-sbom:
    name: Generate SBOM (MS Tool)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # or 7.0/6.0 as per your project

      - name: Restore NuGet packages
        run: dotnet restore eShopOnWeb.sln

      - name: Generate SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b ./config -bc . -pn MyNuGetApp -pv 1.0.0 -ps Philips_test -nsb https://sbom.philips.com -V Verbose


      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom-output/
